### ISSUE TITLE
[Feature request] Volume support

### ISSUE THREAD

**Issue by Nomarian** [winsbe01/roku-cli#1]

**Comment by winsbe01** [comment]
I just pushed an update here (not to PyPi yet) that will allow you to override the default key mappings and add new key mappings.

In your `~/.config/roku/roku.config` file create a new section called `keymap`, and add the new and overridden key/value pairs, where the key is [one of the strings here](https://developer.roku.com/docs/developer-program/debugging/external-control-api.md#keypress-key-values) (I don't think case matters, but when in doubt, lowercase).

for example, if you wanted the keys 1, 3, 5, and 7 to be your directions:
```ini
[keymap]
up=1
down=3
left=5
right=7
```
All other keys will remain defaulted.

I do not have a Roku TV and so can't test the volume controls, but theoretically it should work with `volumeup`, etc. Additional keys should respond, but won't visually appear as part of the remote.

Let me know how you make out!

**Comment by Nomarian** [comment]
Works! again, thanks so much!
